//*****Assignment 2*****
//Course: CS344
//Name: Yu-Wen, Tseng

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <errno.h>

//struct of each room
struct Chamber {
	char  room_name[100];
	int num_connect;
	struct Chamber* connect[6];
	int room_type;  // -1 = start; 0 = middle; 1 = end
};
// create the catalog for the adventure game
void createDir(char **argv, char *catalog){
    pid_t pid = getpid(); //get the unique process ID to avoid coincidind with other catalog name
	snprintf(catalog, 64, "tsengyuw.rooms.%d", pid); // concatenate the file name with process ID
	int createdirResult = mkdir(catalog, 0700); // make a catalog, mode = 0700
}
// initialize the room and copy the given room name to the room_name
struct Chamber *initializeRoom(char *rname){
	struct Chamber *store = malloc(sizeof(struct Chamber));
	strcpy(store->room_name, rname); //char array representing the Room name
    //set the current number of connections to 0 and room type -> MID__ROOM
	store->num_connect = 0;
	store->room_type = 0;
	return store;
}
//create two rooms together
void connectRooms(struct Chamber *froom, struct Chamber *sroom){
    //check if the connection is mutual, and increment the number of connection for each room
	if (froom->num_connect < 6)
	{
        // assure the room x connects to y, then y also connects to x
        if(sroom->num_connect < 6){
		froom->connect[froom->num_connect] = sroom;
		froom->num_connect+=1;
		sroom->connect[sroom->num_connect] = froom;
		sroom->num_connect+=1;
        }
	}
}
// Free memory
void freeRoom(struct Chamber *room){
    int store = 0;
	if (room != 0){
        store =1;
    }
    if(store == 1){
		free(room);
	}
}
//create a solution for the outcomes, which includes the first room for START_ROOM, the other room for END_ROOM
void createoutcome(struct Chamber **roomList){
	int i;
	int outcomeRoomCount = rand() % 6 + 2;	//length = 2 to 7 Rooms
	// -1 = start; 0 = middle; 1 = end
    roomList[0]->room_type = -1;
	roomList[outcomeRoomCount - 1]->room_type = 1;
    i = 0;
    while(i < outcomeRoomCount - 1){
        if (!ConnectionAlreadyExist(roomList[i], roomList[i + 1])){
            connectRooms(roomList[i], roomList[i + 1]);
        }i++;
    }
}
//create the links between the rooms in a given array
void CreateLinks(struct Chamber **roomList){
	int i, overallLinks, randomRoom, matchName, linksExists;
    i = 0;
    while(i < 7){
		overallLinks = rand() % 4 + 3; // set total number of links
		while (roomList[i]->num_connect < overallLinks){
			randomRoom = rand() % 7;
			matchName = strcmp(roomList[i]->room_name, roomList[randomRoom]->room_name);
			linksExists = ConnectionAlreadyExist(roomList[i], roomList[randomRoom]);
            //check if there is no existing links and no other links to connect to itself
			if (matchName != 0){
                if (linksExists != 1){
                    connectRooms(roomList[i], roomList[randomRoom]);
                }
			}
		}i++;
	}
}
//Get the random array of room
void GetRandomRoom(struct Chamber *room, int len){
	int i, randNum;
    i = 0;
    while(i < len){
        //make a random number from 0 to 6, for the use to select random room
		randNum = rand() % len;
		struct Chamber *store = room->connect[i];
		room->connect[i] = room->connect[randNum];
		room->connect[randNum] = store;
        i++;
	}
}
//Random an array of char
void GetRandomChar(char **array, int len){
	int i, randNum;
    i = 0;
    while(i < len){
		randNum = rand() % len;
		char *store = array[i];
		array[i] = array[randNum]; //char arrays is given by random arrays
		array[randNum] = store;
        i++;
	}
}
//Returns 1 if a connection between two rooms are already exists, 0 otherwise
int ConnectionAlreadyExist(struct Chamber *froom, struct Chamber *sroom){
	int i;
    i = 0;
    while(i < froom->num_connect){
		if (froom->connect[i] == sroom){
			return 1;
		}i++;
	}
	return 0;
}
//create 10 room's name and random all the room's name to choose the first 7 as the names of the rooms
//catalog is generated by createDir()
void createGame(char *catalog, char *start, char *end){
	int i, j;
	// list of Chamber's names
    char *RoomNames[10] = {
        "akira",
        "aristotle",
        "bart",
        "benjamin",
        "homer",
        "jasper",
        "lisa",
        "marge",
        "maggie",
        "mary"
    };
	GetRandomChar(RoomNames, 10);//randomly choose the room to each games
	struct Chamber *ChoosedRooms[7];// choose the 7 rooms and copy to new array
    i = 0;
    while(i < 7){
		ChoosedRooms[i] = initializeRoom(RoomNames[i]);
        i++;
	}
	createoutcome(ChoosedRooms); // generate outcome from the random rooms
	CreateLinks(ChoosedRooms);// create links to the choosedrooms
    i = 0;
    while(i<7){
		GetRandomRoom(ChoosedRooms[i], ChoosedRooms[i]->num_connect);
        i++;
	}
    // create files
	char *fileName = malloc(100 * sizeof(char));
    i = 0;
    while(i<7){
		snprintf(fileName, 64, "%s/%s", catalog, ChoosedRooms[i]->room_name);
        FILE *fp;
        fp = fopen(fileName, "w");
		if (fp == NULL){
			fprintf(stderr, "Opening file wrong\n");
		}
		else{
			// print room name to the files
			fprintf(fp, "ROOM NAME: %s\n", ChoosedRooms[i]->room_name);
            j = 0;
            while(j < ChoosedRooms[i]->num_connect){
				fprintf(fp, "CONNECTION %d: %s\n", j + 1,
					ChoosedRooms[i]->connect[j]->room_name);
                j++;
			}
			fprintf(fp, "ROOM TYPE: ");
            // determine the room tyoe
            // -1 = start; 0 = middle; 1 = end
            int store;
            store = ChoosedRooms[i]->room_type;
            switch(store){
                case -1:
                    fprintf(fp, "START_ROOM\n");
                    strcpy(start, ChoosedRooms[i]->room_name);
                    break;
                case 1:
                    fprintf(fp, "END_ROOM\n");
                    strcpy(end, ChoosedRooms[i]->room_name);
                    break;
                default :
                    fprintf(fp, "MID_ROOM\n");
            }
		}
		fclose(fp);
        i++;
	}
	// free Rooms in array of Rooms
    i = 0;
    while(i<7){
		freeRoom(ChoosedRooms[i]);
        i++;
	}
	free(fileName);
}
// read information from the room and save names of room connections to a given array
void roomInfo(struct Chamber *room, FILE *input, char **array){
	char strings[128];
	char connection[128];
	int count;
	char room_type[128];
	// get Chamber name
    fseek(input,0,SEEK_SET);
	while (fgets(strings, 128, input) != NULL){
        //show the room name from each input
		if (sscanf(strings, "ROOM NAME: %[^\n]", room->room_name) == 1){
			break;
		}
	}
	// get rooms and count the number of the links
	fseek(input,0,SEEK_SET);
	count = 0;
	room->num_connect = 0;
	while (fgets(strings, 128, input) != NULL){
		if (sscanf(strings, "CONNECTION %*d: %[^\n]", connection) == 1){
			strcpy(array[count], connection);
			room->num_connect++;
			count++;
		}
	}
    //get room type
    fseek(input,0,SEEK_SET);
    while (fgets(strings, 128, input) != NULL){
        // -1 = start; 0 = middle; 1 = end
        if (sscanf(strings, "ROOM TYPE: %[^\n]", room_type) == 1){
            if (strcmp(room_type, "START_ROOM") == 0){
                room->room_type = -1;
            }
            else if (strcmp(room_type, "END_ROOM") == 0){
                room->room_type = 1;
            }
            else if(strcmp(room_type, "MID_ROOM") == 0){
                room->room_type = 0;
            }
        }
    }
}
int main(int argc, char **argv){
	// generate the random number
	srand(time(NULL));
	// create directories
	char *dirName = malloc(128*sizeof(char));
	createDir(argv, dirName);
	char *start = malloc(128*sizeof(char));
	char *end = malloc(128*sizeof(char));
	createGame(dirName, start, end);
	// free dynamically allocated memory
	free(start);
	free(end);
	free(dirName);
	return 0;
}
